'use strict';
const $=s=>document.querySelector(s);
const escapeHtml=x=>String(x??'未報告').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=x=>x===null||x===undefined?'未提供':Number(x).toFixed(4).replace(/0+$/,'').replace(/\.$/,'');
async function api(path,body,token){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json',...(token?{'X-Demo-Token':token}:{})},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:(data.error||'參數無效或服務未完成請求。'));return data;}
function recipe(){const data=Object.fromEntries(new FormData($('#recipe-form')));for(const key of ['loading_mg_cm2','bn_binder_ratio','dry_temperature_c','dry_hours','test_temperature_c'])data[key]=data[key]===''?null:Number(data[key]);return data;}
function paintAssessment(a){$('#prediction').innerHTML=`<strong>${a.numeric_allowed?'可以做探索性試算；尚未驗證準確度':'這組輸入暫不支持數值預測'}</strong><p>${escapeHtml(a.warning)}</p>${a.reasons.map(r=>`<p>${escapeHtml(r)}</p>`).join('')}<p>同條件平均值基準：${number(a.baseline_mean_mS_cm)} mS/cm；相似配方基準：${number(a.baseline_nearest_mS_cm)} mS/cm；載量線性回歸：${number(a.baseline_linear_mS_cm)} mS/cm。</p><p>找到 ${a.related_records.length} 個同基材文獻案例。相近案例不是這個新配方的實測結果。</p>`;}
async function assess(){const a=await api('/api/assess',recipe());paintAssessment(a);return a;}
$('#recipe-form').addEventListener('submit',async e=>{e.preventDefault();try{await assess();}catch(x){$('#prediction').textContent=x.message;}});
$('#predict').addEventListener('click',async()=>{const button=$('#predict');button.disabled=true;$('#prediction').textContent='Astra 正在分析；最多等待約兩分鐘…';try{const data=await api('/api/predict',recipe(),$('#access-code').value.trim());paintAssessment(data.assessment);if(data.model_response){const m=data.model_response;$('#prediction').insertAdjacentHTML('beforeend',`<hr><span class="tag">${data.cached?'先前真實調用的快取':'本次真實調用'} · ${escapeHtml(m.model)}</span><p class="metric">${m.result.conductivity_mS_cm===null?'模型選擇不給數字':number(m.result.conductivity_mS_cm)+' mS/cm（探索性預測）'}</p><p>${escapeHtml(m.result.preparation_hypothesis)}</p><p>依據：${m.result.supporting_record_ids.map(escapeHtml).join('、')}</p>${m.result.limitations.map(x=>`<p>${escapeHtml(x)}</p>`).join('')}<p class="muted">調用耗時 ${number(m.elapsed_seconds)} 秒。這不是實驗耗時或節省的時間。</p>`);}}catch(x){$('#prediction').textContent=x.message;}finally{button.disabled=false;}});
document.querySelectorAll('[data-case]').forEach(button=>button.addEventListener('click',async()=>{const form=$('#recipe-form');const invitation=$('#access-code').value;form.reset();$('#access-code').value=invitation;if(button.dataset.case==='holdout'){form.elements.bn_form.value='purified_BNNT';form.elements.loading_mg_cm2.value='.5';}if(button.dataset.case==='unsupported'){form.elements.substrate.value='calcium_alginate';form.elements.bn_form.value='BN_nanopowder';form.elements.solvent.value='DMF';form.elements.bn_binder_ratio.value='3';}try{await assess();}catch(x){$('#prediction').textContent=x.message;}}));
async function renderRecords(){const rows=await api('/api/records?q='+encodeURIComponent($('#record-search').value));$('#record-list').innerHTML=rows.map(r=>`<article class="card"><h3>${escapeHtml(r.sample)}</h3><span class="tag">${escapeHtml(r.inputs.substrate)} · ${r.split==='test'?'評測留出案例':r.split==='train'?'訓練案例':'參考／不混合訓練'}</span><p>${escapeHtml(r.cohort)}</p>${Object.entries(r.observations).map(([k,v])=>`<p><strong>${escapeHtml(k)}</strong>：${escapeHtml(v.value)} ${escapeHtml(v.unit)} <span class="muted">${escapeHtml(v.qualifier)}</span></p>`).join('')||'<p>沒有可安全抽取的數值；保留配方與來源。</p>'}<details><summary>配方、條件與缺失</summary><pre>${escapeHtml(JSON.stringify(r.inputs,null,2))}</pre><pre>${escapeHtml(JSON.stringify(r.observations,null,2))}</pre><p>${escapeHtml(r.notes)}</p></details><details><summary>核對原文</summary>${r.evidence_ids.map(id=>`<button type="button" class="evidence-link" data-id="${escapeHtml(id)}">${escapeHtml(id)}</button>`).join('')}<div class="evidence-output"></div></details></article>`).join('');}
$('#record-search').addEventListener('input',()=>{renderRecords().catch(()=>{});});
$('#record-list').addEventListener('click',async e=>{if(!e.target.matches('.evidence-link'))return;const target=e.target.parentElement.querySelector('.evidence-output');try{const item=await api('/api/evidence/'+encodeURIComponent(e.target.dataset.id));target.innerHTML=`<p><a href="${escapeHtml(item.source)}" target="_blank" rel="noopener">查看原始來源</a> · ${escapeHtml(item.locator)}</p><div class="evidence">${escapeHtml(item.text)}</div>`;}catch(x){target.textContent=x.message;}});
async function load(){const[o,s,c,v]=await Promise.all([api('/api/overview'),api('/api/sources'),api('/api/checks'),api('/api/evaluation')]);$('#summary').innerHTML=[[o.source_count,'個來源線索'],[o.study_count,'篇全文研究'],[o.record_count,'個配方案例'],[o.observation_count,'項數值／結果']].map(([n,t])=>`<div class="stat"><strong>${n}</strong>${t}</div>`).join('');$('#limits').textContent=o.limits;$('#privacy').textContent=o.privacy;$('#expiry').textContent=o.expires_at_utc?'本次試用預計截止：'+new Date(o.expires_at_utc).toLocaleString('zh-HK')+'。需主機及網絡持續在線。':'本機預覽；公開試用期限尚未設定。';$('#source-list').innerHTML=s.map(x=>`<article class="source"><a href="${escapeHtml(x.url)}" target="_blank" rel="noopener">${escapeHtml(x.title)}</a><p><span class="tag">${x.access==='full_text_xml'?'已取得全文文字':x.access==='abstract_only'?'僅摘要':'待補背景線索'}</span> ${escapeHtml(x.license)} · ${escapeHtml(x.source_id)}</p><p class="muted">${escapeHtml(x.limitation)}</p></article>`).join('');$('#check-list').innerHTML=c.checks.map(x=>`<article class="card"><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.calculation)} = <strong>${number(x.result)} ${escapeHtml(x.unit)}</strong></p><p>${x.reported!==undefined?'論文寫 '+x.reported+'%；算術不一致，已隔離。':'按文獻數值重算；不是本模型帶來的性能提升。'}</p><p class="muted">${escapeHtml(x.source_id)}</p></article>`).join('');$('#quarantine').innerHTML=c.quarantined.map(x=>`<p><strong>${escapeHtml(x.source_id)}</strong>：${escapeHtml(x.reason)}</p>`).join('');if(v.rows){$('#evaluation').innerHTML=`<div class="table-scroll"><table><thead><tr><th>方法</th><th>預測 mS/cm</th><th>實測 mS/cm</th><th>絕對誤差 mS/cm</th></tr></thead><tbody>${v.rows.map(x=>`<tr><td>${escapeHtml(x.method)}</td><td>${number(x.prediction_mS_cm)}</td><td>${number(x.measured_mS_cm)}</td><td>${number(x.absolute_error_mS_cm)}</td></tr>`).join('')}</tbody></table></div><p>研究數：1；訓練：2；評測：1。跨研究準確度：目前無法估計。</p>`;}else{$('#evaluation').textContent='評測尚未執行。';}await renderRecords();}
const fragment=new URLSearchParams(location.hash.slice(1));if(fragment.has('access')){$('#access-code').value=fragment.get('access');history.replaceState(null,'',location.pathname);}load().catch(x=>{$('#summary').textContent='資料載入未完成：'+x.message;});
