from __future__ import annotations

from functools import lru_cache
import os
import re

os.environ.setdefault('LOKY_MAX_CPU_COUNT', '1')
os.environ.setdefault('OMP_NUM_THREADS', '1')
os.environ.setdefault('OPENBLAS_NUM_THREADS', '1')
os.environ.setdefault('MKL_NUM_THREADS', '1')
os.environ.setdefault('VECLIB_MAXIMUM_THREADS', '1')
os.environ.setdefault('NUMEXPR_NUM_THREADS', '1')

import numpy as np
import pandas as pd
from matminer.featurizers.base import MultipleFeaturizer
from matminer.featurizers.composition import ElementProperty, Stoichiometry
from pymatgen.core import Composition, Element
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import HistGradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupKFold
from sklearn.neighbors import NearestNeighbors

from materials.data import REFERENCE_PROPERTY_COLUMNS, STRUCTURE_SUMMARY_COLUMNS


ATOMIC_NUMBERS = {
    'H': 1, 'B': 5, 'C': 6, 'N': 7, 'O': 8, 'Al': 13, 'Si': 14, 'P': 15,
    'Ga': 31, 'Ge': 32, 'As': 33, 'In': 49, 'Sn': 50, 'Sb': 51, 'Tl': 81, 'Pb': 82, 'Bi': 83,
}
TOY_CANDIDATE_GENERATION_STRATEGY = 'toy_iii_v_demo_grid'
BN_ANCHORED_CANDIDATE_GENERATION_STRATEGY = 'bn_anchored_formula_family_grid'
DEFAULT_CANDIDATE_GENERATION_STRATEGY = BN_ANCHORED_CANDIDATE_GENERATION_STRATEGY
CANDIDATE_SPACE_DEFAULTS = {
    TOY_CANDIDATE_GENERATION_STRATEGY: {
        'candidate_space_name': 'toy_iii_v_demo_grid',
        'candidate_space_kind': 'toy_demo',
        'candidate_space_note': (
            'Formula-only Group 13/15 enumeration without stability, structure, or synthesis constraints.'
        ),
    },
    BN_ANCHORED_CANDIDATE_GENERATION_STRATEGY: {
        'candidate_space_name': 'bn_anchored_formula_family_grid',
        'candidate_space_kind': 'bn_family_demo',
        'candidate_space_note': (
            'BN-containing formula-family grid anchored by BCN / BC2N-style ternary motifs from '
            'the literature and by Si2BN-like motifs observed in the dataset. This is still '
            'formula-only and does not establish structure stability, synthesis feasibility, or '
            'real discovery.'
        ),
    },
}
DEFAULT_CHEMICAL_PLAUSIBILITY_METHOD = 'pymatgen_common_oxidation_state_balance'
DEFAULT_CHEMICAL_PLAUSIBILITY_NOTE = (
    'Formula-level plausibility annotation using pymatgen oxidation-state guesses. This is not a '
    'structure, thermodynamic stability, phonon stability, or synthesis feasibility filter.'
)
DEFAULT_PROPOSAL_SHORTLIST_LABEL = 'family_aware_proposal_shortlist'
DEFAULT_PROPOSAL_SHORTLIST_METHOD = 'ranked_family_cap'
DEFAULT_PROPOSAL_SHORTLIST_NOTE = (
    'A separate advisor-facing proposal shortlist is generated by walking the raw ranking in '
    'order, preserving chemical-plausibility priority, and limiting over-concentration from any '
    'single candidate_family. This shortlist does not replace the full raw ranking artifact.'
)
DEFAULT_EXTRAPOLATION_SHORTLIST_LABEL = 'formula_level_extrapolation_shortlist'
DEFAULT_EXTRAPOLATION_SHORTLIST_METHOD = 'novelty_bucket_ranked_family_cap'
DEFAULT_EXTRAPOLATION_SHORTLIST_NOTE = (
    'A separate advisor-facing novelty shortlist is generated by filtering to formula-level '
    'extrapolation candidates, then walking that ranked subset in order with '
    'chemical-plausibility priority and an explicit candidate_family cap for diversity. This '
    'shortlist does not replace the full raw ranking artifact or the general proposal shortlist.'
)
DEFAULT_STRUCTURE_GENERATION_SEED_LABEL = 'bn_structure_generation_seed_set'
DEFAULT_STRUCTURE_GENERATION_SEED_METHOD = 'bn_analog_reference_exemplar'
DEFAULT_STRUCTURE_GENERATION_SEED_CANDIDATE_SCOPE = (
    'proposal_shortlist_plus_extrapolation_shortlist_plus_bn_centered_top_n'
)
DEFAULT_STRUCTURE_GENERATION_SEED_NOTE = (
    'Builds a structure-generation handoff artifact by attaching shortlisted BN candidates to '
    'nearby BN-containing train+val reference formulas and deterministic exemplar records with '
    'observed structures. This does not generate, relax, or validate new candidate structures; '
    'it only surfaces prototype seeds for downstream substitution, enumeration, or relaxation '
    'workflows.'
)
DEFAULT_DOMAIN_SUPPORT_METHOD = 'train_plus_val_knn_feature_space_support'
DEFAULT_DOMAIN_SUPPORT_DISTANCE_METRIC = 'z_scored_euclidean_rms'
DEFAULT_DOMAIN_SUPPORT_NOTE = (
    'Support is measured in the selected formula-only screening feature space using z-scored '
    'distances to unique train+val formulas. This is a lightweight transparency heuristic, not '
    'a calibrated discovery confidence, uncertainty, or stability estimate.'
)
DOMAIN_SUPPORT_REFERENCE_SPLIT = 'train_plus_val_unique_formulas'
DEFAULT_BN_SUPPORT_METHOD = 'train_plus_val_bn_knn_feature_space_support'
DEFAULT_BN_SUPPORT_DISTANCE_METRIC = 'z_scored_euclidean_rms'
DEFAULT_BN_SUPPORT_NOTE = (
    'Support is measured relative to known BN-containing train+val formulas in the selected '
    'formula-only screening feature space. This is a BN-theme alignment heuristic, not a '
    'calibrated discovery confidence, uncertainty, or structure/stability estimate.'
)
BN_SUPPORT_REFERENCE_SPLIT = 'train_plus_val_bn_unique_formulas'
DEFAULT_BN_ANALOG_EVIDENCE_NOTE = (
    'Observed-property evidence is retrieved from nearby BN-containing train+val formulas. This '
    'is an analog-evidence layer, not a predicted structure, thermodynamic stability, or synthesis '
    'feasibility estimate.'
)
BN_ANALOG_EVIDENCE_REFERENCE_SPLIT = 'train_plus_val_bn_unique_formulas'
DEFAULT_BN_BAND_GAP_ALIGNMENT_NOTE = (
    'Compares the predicted candidate band gap against a local window derived from nearby '
    'BN-containing train+val formulas. This is a heuristic local analog-consistency layer, not '
    'direct structure validation, stability proof, or discovery evidence.'
)
BN_BAND_GAP_ALIGNMENT_REFERENCE_SPLIT = 'train_plus_val_bn_unique_formulas'
DEFAULT_ROBUSTNESS_METHOD = 'group_kfold_by_formula'
DEFAULT_ROBUSTNESS_NOTE = (
    'Runs grouped-by-formula cross-validation across configured feature/model combos so the '
    'evaluation story does not depend on a single holdout split.'
)
DEFAULT_BN_SLICE_BENCHMARK_METHOD = 'leave_one_bn_formula_out'
DEFAULT_BN_SLICE_BENCHMARK_NOTE = (
    'Runs a dedicated BN-focused leave-one-formula-out benchmark because the standard grouped '
    'split can place zero BN formulas in validation/test. This is a small-sample diagnostic for '
    'BN-centered generalization, not a definitive BN-only benchmark.'
)
DEFAULT_BN_FAMILY_BENCHMARK_METHOD = 'leave_one_bn_family_out'
DEFAULT_BN_FAMILY_GROUPING_METHOD = 'reduced_bn_chemical_system'
DEFAULT_BN_FAMILY_BENCHMARK_NOTE = (
    'Runs a BN-family holdout benchmark by leaving out one BN-local chemical family at a time. '
    'The default family definition groups BN formulas by reduced BN chemical system, so BCN-like '
    'systems, BN binaries, and Si-B-N systems are evaluated as separate BN-local families. This '
    'is still a small-sample diagnostic, not a definitive BN-domain benchmark.'
)
DEFAULT_BN_STRATIFIED_ERROR_METHOD = 'group_kfold_bn_vs_non_bn_formula_stratified_error'
DEFAULT_BN_STRATIFIED_ERROR_NOTE = (
    'Runs grouped-by-formula cross-validation and reports separate BN vs non-BN formula-level '
    'errors so the project can show whether BN-containing systems are systematically harder than '
    'the broader 2D-material population.'
)
BN_ANALOG_EVIDENCE_RANKING_NOTE = (
    'Candidates are also paired with observed-property evidence from nearby BN-containing '
    'train+val formulas, including analog band gap, energy-per-atom, exfoliation-energy, and '
    'magnetization summaries. A lightweight analog-validation label then summarizes whether those '
    'nearby BN references stay in more reference-like or more divergent property regimes on the '
    'available metrics. This is analog retrieval, not direct candidate property validation.'
)
DEFAULT_BN_ANALOG_VALIDATION_NOTE = (
    'Compresses BN analog exfoliation / energy / magnetization alignment into a lightweight '
    'vote-fraction validation proxy. This is still a heuristic ranking layer, not direct '
    'structure, thermodynamic stability, or synthesis validation.'
)
BN_BAND_GAP_ALIGNMENT_RANKING_NOTE = (
    'Candidates are also compared against a BN-local analog band-gap window built from nearby '
    'BN-containing train+val formulas. This is a local analog-consistency heuristic, not direct '
    'validation or discovery proof.'
)
DEFAULT_GROUPED_ROBUSTNESS_UNCERTAINTY_METHOD = (
    'selected_formula_only_group_kfold_candidate_prediction_std'
)
DEFAULT_GROUPED_ROBUSTNESS_UNCERTAINTY_NOTE = (
    'Uses grouped-by-formula fold-to-fold prediction spread from the selected formula-only '
    'screening combo as a candidate-ranking robustness penalty. This is a split-robustness '
    'heuristic, not calibrated uncertainty.'
)
BN_ANALOG_VALIDATION_RANKING_NOTE = (
    'A mild BN analog-validation penalty is also applied from the available analog alignment '
    'votes across exfoliation, energy, and magnetization; this remains a heuristic validation '
    'proxy, not direct stability validation.'
)
BN_BAND_GAP_ALIGNMENT_PENALTY_RANKING_NOTE = (
    'A mild BN-local band-gap alignment penalty is also applied when the predicted candidate band '
    'gap falls outside the local BN analog window; this remains a heuristic local analog-'
    'consistency term, not direct validation.'
)
GROUPED_ROBUSTNESS_UNCERTAINTY_RANKING_NOTE = (
    'A mild grouped-fold candidate robustness penalty is also applied from the selected '
    'formula-only screening combo, so candidates that move more across grouped-by-formula '
    'training folds are treated as less robust ranking targets.'
)
BASIC_FEATURE_SET = 'basic_formula_composition'
MATMINER_FEATURE_SET = 'matminer_composition'
FRACTIONAL_COMPOSITION_FEATURE_SET = 'fractional_composition_vector'
STRUCTURE_AWARE_FEATURE_SET = 'matminer_composition_plus_structure_summary'
COMPOSITION_ONLY_FAMILY = 'composition_only'
STRUCTURE_AWARE_FAMILY = 'structure_aware'
DUMMY_FEATURE_SET = 'feature_agnostic_dummy'
PERIODIC_TABLE_SYMBOLS = tuple(str(Element.from_Z(z)) for z in range(1, 119))
FRACTIONAL_COMPOSITION_COLUMNS = tuple(
    f'frac_{symbol.lower()}'
    for symbol in PERIODIC_TABLE_SYMBOLS
)
FORMULA_ONLY_SCREENING_SCOPE = 'candidate_compatible_formula_only'
SELECTED_MODEL_RANKING_BASIS = 'composition_only_selected_model_band_gap'
SELECTED_MODEL_RANKING_NOTE = (
    'Composition-only ranking from the selected formula-based model; not structure-aware.'
)
DISAGREEMENT_RANKING_BASIS = 'composition_only_mean_band_gap_minus_model_disagreement_penalty'
DISAGREEMENT_RANKING_NOTE = (
    'Composition-only demo ranking using a tiny feature/model candidate pool. The score is the '
    'ensemble mean band gap minus a small model-disagreement penalty; disagreement is heuristic '
    'and not calibrated physical uncertainty.'
)
SELECTED_MODEL_WITH_DOMAIN_SUPPORT_PENALTY_RANKING_BASIS = (
    'composition_only_selected_model_band_gap_minus_low_support_penalty'
)
SELECTED_MODEL_WITH_DOMAIN_SUPPORT_PENALTY_RANKING_NOTE = (
    'Composition-only ranking from the selected formula-based model with a mild low-support '
    'penalty in the selected screening feature space; this remains a formula-only heuristic and '
    'not a structure-aware stability estimate.'
)
DISAGREEMENT_WITH_DOMAIN_SUPPORT_PENALTY_RANKING_BASIS = (
    'composition_only_mean_band_gap_minus_model_disagreement_and_low_support_penalties'
)
DISAGREEMENT_WITH_DOMAIN_SUPPORT_PENALTY_RANKING_NOTE = (
    'Composition-only demo ranking using a tiny feature/model candidate pool. The score is the '
    'ensemble mean band gap minus a small model-disagreement penalty and a mild low-support '
    'penalty in the selected screening feature space; both terms are heuristic and not calibrated '
    'physical uncertainty or stability estimates.'
)
SELECTED_MODEL_WITH_BN_SUPPORT_PENALTY_RANKING_BASIS = (
    'composition_only_selected_model_band_gap_minus_bn_support_penalty'
)
SELECTED_MODEL_WITH_BN_SUPPORT_PENALTY_RANKING_NOTE = (
    'Composition-only ranking from the selected formula-based model with a mild BN-local support '
    'penalty in the selected screening feature space; this remains a formula-only heuristic and '
    'not a structure-aware stability estimate.'
)
DISAGREEMENT_WITH_BN_SUPPORT_PENALTY_RANKING_BASIS = (
    'composition_only_mean_band_gap_minus_model_disagreement_and_bn_support_penalties'
)
DISAGREEMENT_WITH_BN_SUPPORT_PENALTY_RANKING_NOTE = (
    'Composition-only demo ranking using a tiny feature/model candidate pool. The score is the '
    'ensemble mean band gap minus a small model-disagreement penalty and a mild BN-local support '
    'penalty; both terms are heuristic and not calibrated physical uncertainty or stability '
    'estimates.'
)
SELECTED_MODEL_WITH_DOMAIN_AND_BN_SUPPORT_PENALTY_RANKING_BASIS = (
    'composition_only_selected_model_band_gap_minus_low_support_and_bn_support_penalties'
)
SELECTED_MODEL_WITH_DOMAIN_AND_BN_SUPPORT_PENALTY_RANKING_NOTE = (
    'Composition-only ranking from the selected formula-based model with mild low-support and '
    'BN-local support penalties in the selected screening feature space; these remain formula-only '
    'heuristics and not structure-aware stability estimates.'
)
DISAGREEMENT_WITH_DOMAIN_AND_BN_SUPPORT_PENALTY_RANKING_BASIS = (
    'composition_only_mean_band_gap_minus_model_disagreement_low_support_and_bn_support_penalties'
)
DISAGREEMENT_WITH_DOMAIN_AND_BN_SUPPORT_PENALTY_RANKING_NOTE = (
    'Composition-only demo ranking using a tiny feature/model candidate pool. The score is the '
    'ensemble mean band gap minus a small model-disagreement penalty together with mild '
    'feature-space low-support and BN-local support penalties; all terms remain heuristic and not '
    'calibrated physical uncertainty or stability estimates.'
)
DOMAIN_SUPPORT_RANKING_NOTE = (
    'Candidates are also annotated with a train+val feature-space domain-support layer: support '
    'comes from z-scored distances to nearby known formulas in the selected screening feature '
    'space, contextualized by the leave-one-out train+val neighborhood-distance distribution.'
)
BN_SUPPORT_RANKING_NOTE = (
    'Candidates are also contextualized against the known BN slice: support comes from z-scored '
    'distances to nearby BN-containing train+val formulas in the selected screening feature '
    'space, contextualized by the leave-one-out BN-neighborhood-distance distribution.'
)
CHEMICAL_PLAUSIBILITY_SCREENING_NOTE = (
    'A lightweight formula-level chemical plausibility screen is applied first using pymatgen '
    'oxidation-state guesses; candidates that pass are prioritized ahead of candidates without a '
    'charge-balanced common oxidation-state assignment.'
)
NOVELTY_BUCKET_TRAIN_PLUS_VAL_REDISCOVERY = 'train_plus_val_rediscovery'
NOVELTY_BUCKET_HELD_OUT_KNOWN_FORMULA = 'held_out_known_formula'
NOVELTY_BUCKET_FORMULA_LEVEL_EXTRAPOLATION = 'formula_level_extrapolation'
NOVELTY_BUCKET_PRIORITY = {
    NOVELTY_BUCKET_TRAIN_PLUS_VAL_REDISCOVERY: 1,
    NOVELTY_BUCKET_HELD_OUT_KNOWN_FORMULA: 2,
    NOVELTY_BUCKET_FORMULA_LEVEL_EXTRAPOLATION: 3,
}
NOVELTY_BUCKET_NOTE = {
    NOVELTY_BUCKET_TRAIN_PLUS_VAL_REDISCOVERY: (
        'Seen in train+val, so this is rediscovery / in-domain replay rather than formula-level '
        'extrapolation.'
    ),
    NOVELTY_BUCKET_HELD_OUT_KNOWN_FORMULA: (
        'Seen elsewhere in the dataset but not in train+val, so this is a held-out-known formula '
        'rather than a new formula-level candidate.'
    ),
    NOVELTY_BUCKET_FORMULA_LEVEL_EXTRAPOLATION: (
        'Unseen in the dataset, so this is formula-level extrapolation within the current demo '
        'candidate space. This still does not establish real materials discovery.'
    ),
}
NOVELTY_ANNOTATION_RANKING_NOTE = (
    'Novelty is tracked only at the formula level: use the novelty bucket fields to separate '
    'train+val rediscovery, held-out-known formulas, and unseen formulas. This transparency layer '
    'does not turn the demo ranking into validated discovery.'
)
FEATURE_SET_METADATA = {
    BASIC_FEATURE_SET: (
        COMPOSITION_ONLY_FAMILY,
        True,
        'Hand-written control baseline from formula tokens and a small atomic-number lookup.',
    ),
    MATMINER_FEATURE_SET: (
        COMPOSITION_ONLY_FAMILY,
        True,
        'Curated matminer composition descriptors from pymatgen Composition objects using '
        'Stoichiometry plus selected Magpie elemental-property statistics.',
    ),
    FRACTIONAL_COMPOSITION_FEATURE_SET: (
        COMPOSITION_ONLY_FAMILY,
        True,
        'Raw fractional-composition vector across the periodic table. This is intended for '
        'learned neural composition models and keeps hypothetical formula screening candidate-'
        'compatible without assuming structure inputs.',
    ),
    STRUCTURE_AWARE_FEATURE_SET: (
        STRUCTURE_AWARE_FAMILY,
        False,
        'Matminer composition descriptors plus compact lattice/layer summary columns derived '
        'from cached atoms and lattice information.',
    ),
    DUMMY_FEATURE_SET: (
        'feature_agnostic_baseline',
        False,
        'Dummy regressor baseline that ignores composition features.',
    ),
}
MODEL_FEATURE_SET_COMPATIBILITY = {
    'torch_fractional_attention': {FRACTIONAL_COMPOSITION_FEATURE_SET},
    'torch_sparse_fractional_attention': {FRACTIONAL_COMPOSITION_FEATURE_SET},
    'torch_roost_like': {FRACTIONAL_COMPOSITION_FEATURE_SET},
}
BASIC_FEATURE_COLUMNS = (
    'n_elements',
    'sum_z',
    'max_z',
    'min_z',
    'mean_z',
    'contains_B',
    'contains_N',
)
MATMINER_SELECTED_RAW_LABELS = (
    '0-norm',
    '2-norm',
    '3-norm',
    'MagpieData mean Number',
    'MagpieData range Number',
    'MagpieData mean MendeleevNumber',
    'MagpieData range MendeleevNumber',
    'MagpieData mean AtomicWeight',
    'MagpieData range AtomicWeight',
    'MagpieData mean Row',
    'MagpieData range Row',
    'MagpieData mean Column',
    'MagpieData range Column',
    'MagpieData mean Electronegativity',
    'MagpieData range Electronegativity',
    'MagpieData mean NsValence',
    'MagpieData mean NpValence',
    'MagpieData mean NdValence',
    'MagpieData mean NfValence',
)
STRUCTURE_AWARE_REQUIRED_COLUMNS = STRUCTURE_SUMMARY_COLUMNS
BASE_PASSTHROUGH_COLUMNS = (
    'record_id',
    'source',
    'formula',
    'target',
    *REFERENCE_PROPERTY_COLUMNS,
    'candidate_space_name',
    'candidate_space_kind',
    'candidate_generation_strategy',
    'candidate_space_note',
    'candidate_family',
    'candidate_template',
    'candidate_family_note',
)

